
title: Free Vbucks - Generate Fortnite V-Bucks 2020 | NoHumanVerification
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Getting free vbucks can be a hassle in Fortnite, learn these easy ways to get them using our trustworthy Generator. 
author:             Start Bootstrap
baseurl:            "startbootstrap-clean-blog-jekyll/"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   SBootstrap  
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
  - jekyll-seo-tag