
title: 'Free Vbucks - Generate Fortnite V-Bucks 2020 | NoHumanVerification'
email: your-email@example.com

author:             Free vbucks
baseurl:            ""
url:                "https://startbootstrap.github.io"

# Social Profiles

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap 
  - jekyll-seo-tag